jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enable debugging
        run: set -x  # This will show each command as it runs

      - name: Send webhook notification
        run: |
          curl -v -X POST "https://telex-cicd.onrender.com/notifications/github" \
          -H "X-API-KEY: ${{ secrets.API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "repository": "${{ github.repository }}",
            "workflow": "${{ github.workflow }}",
            "status": "${{ job.status }}",
            "actor": "${{ github.actor }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "ref": "${{ github.ref }}"
          }'